# Generated by Django 5.1 on 2024-08-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scam_type', models.CharField(choices=[('social_media', 'Social Media Scam'), ('phone_call', 'Phone Call Scam'), ('website', 'Website Scam'), ('email', 'Email Scam'), ('other', 'Other Scam')], max_length=50)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
